// GENERATED by scripts/embed-clips.mjs — do not edit by hand.
export const CLIPS = [
  {
    "id": "brand",
    "name": "DeepSeek 品牌片头",
    "ext": ".mp4",
    "bytes": 1308725,
    "sha256": "b22de4810e195b50",
    "b64": 1744968
  },
  {
    "id": "cyberpunk",
    "name": "DeepSeek 赛博朋克片头",
    "ext": ".mp4",
    "bytes": 1856280,
    "sha256": "beabf5956e0b467e",
    "b64": 2475040
  },
  {
    "id": "awakening",
    "name": "DeepSeek 数字角色苏醒",
    "ext": ".mp4",
    "bytes": 2600325,
    "sha256": "ff5afe0dabc16e09",
    "b64": 3467100
  },
  {
    "id": "startup",
    "name": "DeepSeek 启动问题",
    "ext": ".mp4",
    "bytes": 3305269,
    "sha256": "ba72c501021444cd",
    "b64": 4407028
  }
]
