import { readFileSync, writeFileSync, statSync } from "node:fs"
import { createHash } from "node:crypto"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const CLIPS = [
  { id: "brand", file: "media/deepseek-brand-intro.mp4", name: "DeepSeek 品牌片头" },
  { id: "cyberpunk", file: "media/deepseek-cyberpunk-intro.mp4", name: "DeepSeek 赛博朋克片头" },
  { id: "awakening", file: "media/deepseek-awakening-intro.mp4", name: "DeepSeek 数字角色苏醒" },
  { id: "startup", file: "media/deepseek-startup-intro.mp4", name: "DeepSeek 启动问题" },
]

// faststart: moov must sit before mdat, or the browser waits for the whole file.
const hasFaststart = (buf) => {
  const head = buf.subarray(0, Math.min(65536, buf.length)).toString("latin1")
  const moov = head.indexOf("moov")
  if (moov === -1) return false
  const mdat = head.indexOf("mdat")
  return mdat === -1 || moov < mdat
}

const meta = []
const data = {}
for (const clip of CLIPS) {
  const buf = readFileSync(join(ROOT, clip.file))
  if (!hasFaststart(buf)) throw new Error(`${clip.file} lacks faststart — remux before embedding`)
  data[clip.id] = buf.toString("base64")
  meta.push({
    id: clip.id,
    name: clip.name,
    ext: ".mp4",
    bytes: buf.length,
    sha256: createHash("sha256").update(buf).digest("hex").slice(0, 16),
    b64: data[clip.id].length,
  })
}

writeFileSync(
  join(ROOT, "lib", "clips.meta.js"),
  `// GENERATED by scripts/embed-clips.mjs — do not edit by hand.\n` +
    `export const CLIPS = ${JSON.stringify(meta, null, 2)}\n`,
  "utf8",
)
writeFileSync(
  join(ROOT, "lib", "clips.data.js"),
  `// GENERATED by scripts/embed-clips.mjs — do not edit by hand.\n` +
    `// Base64 of the clips the plugin carries. Imported lazily so the host does not\n` +
    `// parse ${(meta.reduce((n, m) => n + m.b64, 0) / 1024 / 1024).toFixed(1)}MB of data at startup.\n` +
    CLIPS.map((c) => `export const ${c.id} = "${data[c.id]}"`).join("\n") +
    "\n",
  "utf8",
)

let raw = 0
let b64 = 0
for (const m of meta) {
  raw += m.bytes
  b64 += m.b64
  console.log(`  ${m.id.padEnd(10)} ${String(m.bytes).padStart(9)} bytes -> base64 ${String(m.b64).padStart(9)} chars  sha=${m.sha256}`)
}
console.log(`\n  raw total      : ${(raw / 1024 / 1024).toFixed(2)} MB`)
console.log(`  embedded total : ${(b64 / 1024 / 1024).toFixed(2)} MB  (+${Math.round((b64 / raw - 1) * 100)}%)`)